name: Provision Dev Center

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'The environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

permissions:
  id-token: write
  actions: write
  contents: write
  
jobs:
  deploy-infra-dev:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7  

    - name: Login via Az module
      uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Generate Deployment Name
      id: deploymentName
      run: |
        deploymentName="deployment-gh-${{ github.run_id }}"  
        echo "deploymentName=$deploymentName" >> "$GITHUB_OUTPUT"

    - name: Validate Bicep file
      env:
        deploymentName: ${{ steps.deploymentName.outputs.deploymentName }}
        resourceGroupName: ${{ vars.RESOURCE_GROUP }}
      run: |
        az deployment group validate --only-show-errors -n $deploymentName -g $resourceGroupName --template-file ./infra/main.bicep > /dev/null

    - name: Run What-If Deployment
      env:
        deploymentName: ${{ steps.deploymentName.outputs.deploymentName }}
        resourceGroupName: ${{ vars.RESOURCE_GROUP }}
      run: |
        az deployment group what-if --only-show-errors --no-pretty-print -n $deploymentName -g $resourceGroupName --template-file ./infra/main.bicep > /dev/null

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      id: deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.RESOURCE_GROUP }}
        template: ./infra/main.bicep
        parameters: 'location=${{ vars.LOCATION }} catalogs=@catalogs.json'
        failOnStdErr: false
        deploymentName: ${{ steps.deploymentName.outputs.deploymentName }}
        scope: 'resourcegroup'

    - uses: actions/github-script@v7
      name: Set Environment Variables
      with:
        github-token: ${{ secrets.MANAGE_ENV_VARS_PAT }}
        retries: 3
        debug: true
        retry-exempt-status-codes: 400,401
        script: |
          const { default: createVariables } = await import('${{ github.workspace }}/src/create-Variables.js')
          const environment = '${{ github.event.inputs.env }}'
          const variables = [
              {
                  name: 'GALLERY_NAME',
                  value: '${{ steps.deploy.outputs.galleryName }}'
              },
              {
                  name: 'DEV_CENTER_NAME',
                  value: '${{ steps.deploy.outputs.devCenterName }}'
              },
              {
                  name: 'IMAGE_BUILDER_MANAGED_IDENTITY_NAME',
                  value: '${{ steps.deploy.outputs.imageBuilderId }}'
              },
              {
                  name: 'BASE_DEV_BOX_DEFINITION_NAME',
                  value: '${{ steps.deploy.outputs.devBoxDefinitionName }}'
              },
              {
                  name: 'DEV_CENTER_ATTACHED_NETWORK',
                  value: '${{ steps.deploy.outputs.devCenterAttachedNetworkName }}'
              }
          ]
          await createVariables(github, context, environment, variables)        